#! /bin/bash
export PATH=$PATH:/opt/venv/bin:/usr/kerberos/sbin:/usr/kerberos/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/us$
alias  chdir="cd /opt/cvkiosk"
cd /opt/cvkiosk || return
startx &
/usr/bin/nice -n -5 /opt/venv/bin/python -c 'import main' && xrandr -d :0